Repository WE-SAVE-UMC/BE, pull requests merged in 2024-08, with the labels that each got.

#7 feature: 유효한 닉네임 확인 API 구현완료
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/repository/UserRepository.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
Labels: ✨feature

#10 feature: 전화번호 인증코드 요청 API 구현 완료
  build.gradle
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserAuthResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/UserConverter.java
  src/main/java/com/example/we_save/sms/SmsUtil.java
  src/main/java/com/example/we_save/sms/controller/SmsController.java
  src/main/java/com/example/we_save/sms/controller/request/SmsRequestDto.java
  src/main/java/com/example/we_save/sms/controller/response/SmsResponseDto.java
  src/main/java/com/example/we_save/sms/service/SmsCommandService.java
  src/main/java/com/example/we_save/sms/service/SmsCommandServiceImpl.java
Labels: ✨feature

#11 feature: 전화번호 유효한 인증코드 확인 API 구현 완료
  src/main/java/com/example/we_save/sms/controller/SmsController.java
  src/main/java/com/example/we_save/sms/service/VerificationCodeService.java
  src/main/java/com/example/we_save/sms/service/VerificationCodeServiceImpl.java
Labels: ✨feature

#19 1 feat 로그인 구현
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/request/UserAuthRequestDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserAuthResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/UserConverter.java
  src/main/java/com/example/we_save/domain/user/entity/User.java
  src/main/java/com/example/we_save/domain/user/repository/UserRepository.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
  src/main/java/com/example/we_save/jwt/JWTFilter.java
  src/main/java/com/example/we_save/jwt/JWTUtil.java
  src/main/java/com/example/we_save/jwt/LoginFilter.java
  src/main/java/com/example/we_save/jwt/config/SecurityConfig.java
  src/main/java/com/example/we_save/jwt/dto/CustomUserDetails.java
  src/main/java/com/example/we_save/jwt/service/CustomUserDetailsService.java
  src/test/java/com/example/we_save/WeSaveApplicationTests.java
Labels: ✨feature

#25 feature: 모든 깊이의 지역 entity 구현
  src/main/java/com/example/we_save/domain/region/entity/EupmyeondongRegion.java
  src/main/java/com/example/we_save/domain/region/entity/SidoRegion.java
  src/main/java/com/example/we_save/domain/region/entity/SigunguRegion.java
  src/main/java/com/example/we_save/domain/region/repository/EupmyeondongRepository.java
  src/main/java/com/example/we_save/domain/region/repository/SidoRepository.java
  src/main/java/com/example/we_save/domain/region/repository/SigunguRepository.java
Labels: ✨feature

#28 fix: Post Entity에 매핑 추가
  src/main/java/com/example/we_save/domain/post/entity/Post.java
  src/main/java/com/example/we_save/domain/post/entity/PostImage.java
Labels: fix

#29 15 feat 마이페이지 프로필 조회 api 구현
  src/main/java/com/example/we_save/config/SwaggerConfig.java
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/request/UserAuthRequestDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserAuthResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/UserConverter.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
Labels: ✨feature

#32 feature: 마이페이지 프로필 수정 API 구현완료(#16)
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/request/UserAuthRequestDto.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
Labels: ✨feature

#37 36 feat mypage setting heartregion crud
  src/main/java/com/example/we_save/apiPayload/util/RegionUtil.java
  src/main/java/com/example/we_save/domain/region/application/HeartService.java
  src/main/java/com/example/we_save/domain/region/application/HeartServiceImpl.java
  src/main/java/com/example/we_save/domain/region/controller/HeartRegionController.java
  src/main/java/com/example/we_save/domain/region/controller/request/RegionNameRequestDto.java
  src/main/java/com/example/we_save/domain/region/controller/response/HeartRegionResponseDto.java
  src/main/java/com/example/we_save/domain/region/controller/response/RegionIdResponseDto.java
  src/main/java/com/example/we_save/domain/region/entity/EupmyeondongRegion.java
  src/main/java/com/example/we_save/domain/region/entity/HeartRegion.java
  src/main/java/com/example/we_save/domain/region/repository/EupmyeondongRepository.java
  src/main/java/com/example/we_save/domain/region/repository/HeartRegionRepository.java
Labels: bug, ✨feature, fix

#39 feature jwt payload util
  build.gradle
  src/main/java/com/example/we_save/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/repository/UserRepository.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
  src/main/java/com/example/we_save/jwt/JWTFilter.java
  src/main/java/com/example/we_save/jwt/LoginFilter.java
  src/main/java/com/example/we_save/jwt/config/SecurityConfig.java
  src/main/java/com/example/we_save/jwt/dto/CustomUserDetails.java
  src/main/java/com/example/we_save/jwt/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/we_save/jwt/exception/code/JWTErrorCode.java
  src/main/java/com/example/we_save/jwt/service/CustomUserDetailsService.java
Labels: ✨feature

#44 Feature: 좌표 데이터로 두 지점 간의 거리 구하기
  src/main/java/com/example/we_save/apiPayload/util/RegionUtil.java
Labels: ✨feature

#46 [FEAT] 메인페이지 조회 기능
  src/main/java/com/example/we_save/apiPayload/util/RegionUtil.java
  src/main/java/com/example/we_save/domain/home/application/HomeService.java
  src/main/java/com/example/we_save/domain/home/application/HomeServiceImpl.java
  src/main/java/com/example/we_save/domain/home/controller/HomeController.java
  src/main/java/com/example/we_save/domain/home/controller/request/HomeLocationRequestDto.java
  src/main/java/com/example/we_save/domain/home/controller/response/HomeResponseDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/HotPostHomeResponseDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/NearPostHomeResponseDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/PostResponseDtoWithComments.java
  src/main/java/com/example/we_save/domain/post/entity/Category.java
  src/main/java/com/example/we_save/domain/post/entity/Post.java
  src/main/java/com/example/we_save/domain/post/entity/PostStatus.java
  src/main/java/com/example/we_save/domain/post/repository/PostRepository.java
  src/main/java/com/example/we_save/domain/region/application/HeartServiceImpl.java
  src/main/java/com/example/we_save/domain/user/controller/UserController.java
Labels: ✨feature

#71 [FEAT] 차단해제 api 구현
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/UserController.java
  src/main/java/com/example/we_save/domain/user/controller/response/BlockResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/BlockConverter.java
  src/main/java/com/example/we_save/domain/user/service/UserService.java
  src/main/java/com/example/we_save/domain/user/service/UserServiceImpl.java
Labels: ✨feature

#67 [FEAT] 메인페이지 검색 기능
  src/main/java/com/example/we_save/domain/countermeasure/controller/response/CountermeasureResponseDto.java
  src/main/java/com/example/we_save/domain/countermeasure/entity/Countermeasure.java
  src/main/java/com/example/we_save/domain/countermeasure/repository/CountermeasureRepository.java
  src/main/java/com/example/we_save/domain/home/application/HomeService.java
  src/main/java/com/example/we_save/domain/home/application/HomeServiceImpl.java
  src/main/java/com/example/we_save/domain/home/controller/HomeController.java
Labels: ✨feature

#69 Feature: 마이페이지 - 댓글 조회 기능 구현
  src/main/java/com/example/we_save/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/we_save/domain/user/controller/UserController.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserCommentResponseDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserPostResponseDto.java
  src/main/java/com/example/we_save/domain/user/service/UserService.java
  src/main/java/com/example/we_save/domain/user/service/UserServiceImpl.java
Labels: ✨feature

#72 [FEAT] 차단목록보기 API 구현
  src/main/java/com/example/we_save/domain/user/controller/UserController.java
  src/main/java/com/example/we_save/domain/user/controller/request/BlockRequestDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/BlockResponseDto.java
  src/main/java/com/example/we_save/domain/user/repository/BlockRepository.java
  src/main/java/com/example/we_save/domain/user/service/UserService.java
  src/main/java/com/example/we_save/domain/user/service/UserServiceImpl.java
Labels: ✨feature

#88 [REFACTOR] 프로필 이미지 업로드, 파일서버 연동
  Users/choiaerim/Desktop/dev/BE/src/main/resources/static/profile_image
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/request/UserAuthRequestDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/BlockResponseDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserAuthResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/BlockConverter.java
  src/main/java/com/example/we_save/domain/user/converter/UserConverter.java
  src/main/java/com/example/we_save/domain/user/entity/User.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
  src/main/java/com/example/we_save/image/entity/Image.java
  src/main/java/com/example/we_save/image/repository/ImageRepository.java
  src/main/java/com/example/we_save/image/service/ImageService.java
  src/main/java/com/example/we_save/image/service/ImageServiceImpl.java
  src/main/resources/static/profile.jpg
Labels: ✨feature, ♻️refactor

#76 [FEAT] 비밀번호 재설정 API 구현 및 회원가입 API 비밀번호 유효성 검사 추가
  src/main/java/com/example/we_save/apiPayload/util/PasswordUtil.java
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
Labels: ✨feature, ♻️refactor

#92 [REFACTOR] 게시글 이미지 조회,등록,수정,삭제 파일서버 연동 리팩토링
  Users/choiaerim/Desktop/dev/BE/src/main/resources/static/profile_image
  src/main/java/com/example/we_save/domain/post/applicaiton/PostImageService.java
  src/main/java/com/example/we_save/domain/post/applicaiton/PostImageServiceImpl.java
  src/main/java/com/example/we_save/domain/post/applicaiton/PostService.java
  src/main/java/com/example/we_save/domain/post/applicaiton/PostServiceImpl.java
  src/main/java/com/example/we_save/domain/post/controller/PostController.java
  src/main/java/com/example/we_save/domain/post/controller/request/PostRequestDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/DomesticPostDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/HotPostHomeResponseDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/NearPostHomeResponseDto.java
  src/main/java/com/example/we_save/domain/post/controller/response/PostDto.java
  src/main/java/com/example/we_save/domain/post/entity/Post.java
  src/main/java/com/example/we_save/domain/post/entity/PostImage.java
  src/main/java/com/example/we_save/domain/post/repository/PostImageRepository.java
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserAuthResponseDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserCommentResponseDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserPostResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/UserConverter.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
  src/main/java/com/example/we_save/image/entity/Image.java
  src/main/java/com/example/we_save/image/service/ImageService.java
  src/main/java/com/example/we_save/image/service/ImageServiceImpl.java
Labels: ♻️refactor

#115 [FIX] 프로필 사진 수정 버그
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
Labels: 🔨fix

#117 [FIX] 게시판 사진 수정 버그
  src/main/java/com/example/we_save/domain/comment/controller/CommentController.java
  src/main/java/com/example/we_save/domain/post/controller/PostController.java
Labels: 🔨fix

#121 [FEAT] 회원탈퇴 API구현
  src/main/java/com/example/we_save/domain/user/controller/UserAuthController.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserAuthResponseDto.java
  src/main/java/com/example/we_save/domain/user/converter/UserConverter.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandService.java
  src/main/java/com/example/we_save/domain/user/service/UserAuthCommandServiceImpl.java
  src/main/java/com/example/we_save/jwt/JWTUtil.java
  src/main/java/com/example/we_save/jwt/LoginFilter.java
Labels: ✨feature, ♻️refactor

#129 [Refactor] Dto 데이터 추가
  src/main/java/com/example/we_save/domain/user/controller/response/UserCommentResponseDto.java
  src/main/java/com/example/we_save/domain/user/controller/response/UserPostResponseDto.java
Labels: ♻️refactor

#130 [Feat] 광고 Dto 추가
  src/main/java/com/example/we_save/domain/ads/application/AdsService.java
  src/main/java/com/example/we_save/domain/ads/application/AdsServiceImpl.java
  src/main/java/com/example/we_save/domain/ads/controller/AdsController.java
  src/main/java/com/example/we_save/domain/ads/repository/AdsRepository.java
  src/main/java/com/example/we_save/domain/home/application/HomeServiceImpl.java
  src/main/java/com/example/we_save/domain/home/controller/response/HomeResponseDto.java
Labels: ✨feature
